version: '3.8'

services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite_lib_container
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: storybook_lib_container
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run storybook -- --ci --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true