// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from "eslint-plugin-storybook";

import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    'logs',
    '*.log',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'lerna-debug.log*',
    '.pnpm-debug.log*',
    'report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json',
    'pids',
    '*.pid',
    '*.seed',
    '*.pid.lock',
    'lib-cov',
    'coverage',
    '*.lcov',
    '.nyc_output',
    '.grunt',
    'bower_components',
    '.lock-wscript',
    'build/Release',
    'node_modules/',
    'jspm_packages/',
    'web_modules/',
    '*.tsbuildinfo',
    '.npm',
    '.npmrc',
    '.eslintcache',
    '.stylelintcache',
    'rpt2_cache/',
    'rts2_cache_cjs/',
    'rts2_cache_es/',
    'rts2_cache_umd/',
    '.node_repl_history',
    '*.tgz',
    '.yarn-integrity',
    '.env',
    '.env.development.local',
    '.env.test.local',
    '.env.production.local',
    '.env.local',
    '.cache',
    '.parcel-cache',
    '.next',
    'out',
    '.nuxt',
    'dist',
    '.cache/',
    '.vuepress/dist',
    '.temp',
    '.docusaurus',
    '.serverless/',
    '.fusebox/',
    '.dynamodb/',
    '.tern-port',
    '.vscode-test',
    '.yarn/cache',
    '.yarn/unplugged',
    '.yarn/build-state.yml',
    '.yarn/install-state.gz',
    '.pnp.*',
    '.webpack/',
    '.svelte-kit',
    'Dockerfile',
    'Dockerfile.dev',
    '.dockerignore',
    '.npmrc',
    'Jenkinsfile',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
])
